CREATE TABLE IF NOT EXISTS {tablename} AS
    SELECT * FROM read_csv('{csv_path}', header=true, columns = {{
        "dt":"TIMESTAMP",
        "count_of_uplimit":"USMALLINT",
        "count_of_downlimit":"USMALLINT",
        "count_of_yiziup":"USMALLINT",
        "count_of_yizidown":"USMALLINT",
        "ratio_of_uplimit":"FLOAT",
        "ratio_of_downlimit":"FLOAT",
        "ratio_of_yiziup":"FLOAT",
        "ratio_of_yizidown":"FLOAT",
        "lb1":"USMALLINT",
        "lb2":"USMALLINT",
        "lb3":"USMALLINT",
        "lb4":"USMALLINT",
        "lb5":"USMALLINT",
        "lb6":"USMALLINT",
        "lb7":"USMALLINT",
        "lb8":"USMALLINT",
        "lb9":"USMALLINT",
        "lb10":"USMALLINT",
        "lb11":"USMALLINT",
        "lb12":"USMALLINT",
    }});
